---
# tasks file for orthanc-docker

- name: Create data container
  docker_container:
    name: '{{ orthanc_container_name + "-data" }}'
    image: busybox
    state: present
    volumes:
      - '/var/lib/orthanc/db'
  when: orthanc_use_data_container

- name: "Create {{ orthanc_config_dir }} directory for config"
  file:
    path: '{{ orthanc_config_dir }}'
    state: directory
  become: yes

- name: 'Add {{ orthanc_config_dir }}/orthanc.json'
  template:
    src: orthanc.json.j2
    dest: '{{ orthanc_config_dir + "/orthanc.json" }}'
  become: yes
  notify: stop_orthanc_container

- name: "Pull Orthanc image: {{ orthanc_docker_image }}"
  docker_image:
    name: '{{ orthanc_docker_image }}'
    tag:  '{{ orthanc_docker_image_tag }}'

- name: Setup Orthanc container
  docker_container:
    name:  '{{ orthanc_container_name }}'
    image: '{{ orthanc_docker_image + ":" + orthanc_docker_image_tag }}'
    state:  started
    ports:
      - '{{ orthanc_api_port }}:8042'
      - '{{ orthanc_dicom_port }}:4242'

    volumes_from: '{{ [orthanc_container_name + "-data"] if orthanc_use_data_container else [] }}'

    volumes: '{{ ["{}/orthanc.json:/etc/orthanc/orthanc.json:ro".format(orthanc_config_dir)] + ([orthanc_data_dir + ":/var/lib/orthanc/db:z"] if not orthanc_use_data_container else []) }}'
    links: '{{ [orthanc_pg_host] if orthanc_pg_backend else [] }}'
    env:
      TZ: '{{ orthanc_container_timezone }}'
  register: orthanc_container

- meta: flush_handlers

- name: Wait until Orthanc is available
  wait_for: port={{ orthanc_api_port }} delay=3
  when: orthanc_container.changed
