---
# tasks file for orthanc-docker

- name: Create data container
  docker_container:
    name: '{{ orthanc_container_name }}-data'
    image: busybox
    state: present
  when: orthanc_use_data_container

- name: Create /etc/orthanc directory for config
  file:
    path: /etc/orthanc
    state: directory
  become: yes

- name: Add orthanc.json
  template:
    src: orthanc.json.j2
    dest: /etc/orthanc/orthanc.json
  become: yes

- name: Pull Orthanc image
  docker_image:
    name: '{{ orthanc_docker_image }}'
    tag:  '{{ orthanc_docker_image_tag }}'

- name: Setup Orthanc container
  docker_container:
    name:  '{{ orthanc_container_name }}'
    image: '{{ orthanc_docker_image }}:{{ orthanc_docker_tag }}'
    state:  started
    memory: '{{ container_memory_limit | default(omit) }}'
    ports:
      - '{{ orthanc_api_port }}:8042'
      - '{{ orthanc_dicom_port }}:4242'
    volumes_from:
      - '{{ ( orthanc_use_data_container and orthanc_container_name + "-data" ) | default(omit) }}'
    volumes:
      - '/etc/orthanc/orthanc.json:/etc/orthanc/orthanc.json:ro'
      - '{{ not orthanc_use_data_container and ( orthanc_data_dir + ":/etc/orthanc/db" ) | default(omit) }}'
    links:
      - '{{ orthanc_pg_backend and orthanc_pg_host | default(omit) }}'
    env:
      TZ: '{{ orthanc_container_timezone }}'
  register: orthanc_container

- name: Wait until Orthanc is available
  wait_for: port={{ orthanc_api_port }} delay=3
  when: postgres_container.changed
